BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Stock_Update";
CREATE TABLE IF NOT EXISTS "Stock_Update" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Quantity"	INTEGER,
	"Price"	INTEGER,
	"Datetime"	TEXT,
	"Last_Available"	INTEGER,
	"ProductID"	INTEGER
);
DROP TABLE IF EXISTS "Products";
CREATE TABLE IF NOT EXISTS "Products" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT,
	"Price"	INTEGER,
	"ImageUrl"	TEXT,
	"CategoryID"	INTEGER,
	"UnitID"	TEXT,
	"ShortCode"	TEXT
);
DROP TABLE IF EXISTS "SaleItem";
CREATE TABLE IF NOT EXISTS "SaleItem" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"SaleID"	INTEGER,
	"ProductID"	INTEGER,
	"Price"	INTEGER,
	"Quantity"	INTEGER
);
DROP TABLE IF EXISTS "Sale";
CREATE TABLE IF NOT EXISTS "Sale" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Datetime"	TEXT,
	"CustomerID"	INTEGER,
	"TotalAmount"	INTEGER,
	"Discount"	INTEGER,
	"PaidAmount"	INTEGER,
	"Balance"	INTEGER
);
DROP TABLE IF EXISTS "Customer";
CREATE TABLE IF NOT EXISTS "Customer" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT,
	"Phone"	TEXT,
	"Date"	TEXT,
	"Balance"	INTEGER
);
DROP TABLE IF EXISTS "Stock";
CREATE TABLE IF NOT EXISTS "Stock" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Product_Id"	INTEGER,
	"Quantity"	INTEGER
);
DROP TABLE IF EXISTS "Expenses";
CREATE TABLE IF NOT EXISTS "Expenses" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT,
	"Amount"	INTEGER,
	"Datetime"	TEXT,
	"Comment"	TEXT
);
DROP TABLE IF EXISTS "Categories";
CREATE TABLE IF NOT EXISTS "Categories" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT
);
DROP TABLE IF EXISTS "Units";
CREATE TABLE IF NOT EXISTS "Units" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT,
	"Unit_prefix"	TEXT
);
DROP TABLE IF EXISTS "Users";
CREATE TABLE IF NOT EXISTS "Users" (
	"Id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"Name"	TEXT,
	"Username"	TEXT,
	"Password"	TEXT,
	"Role"	INTEGER
);
COMMIT;
